### ISSUE TITLE
Rugby matches not showing 

### ISSUE THREAD

**Issue by tdbnz-coding** [matthuisman/plugin.video.spark.sport#1]
Hi Team

There is a issue no semi final games are on spark sport kodi addon meaning we can't see the stream for games and meaning we have to pull the plug and use spark app

Could be a api change normally matches are on the what's on screen the all black or England match was not on addon 

Hopefully there is a fix 

Cheers

**Comment by matthuisman** [comment]
I can see the QF matches under RWC2019 > RWC Full Matches
I can also see the upcoming games under RWC2019 > What's On

**Comment by matthuisman** [comment]
Hi. I found the "Whats On" in the main menu wasn't listing a few events.
I have fixed that with this commit: https://github.com/matthuisman/plugin.video.spark.sport/commit/dbd1a57e5f449debbbe4374b040b7ff8684546b1
(it now shows exactly what the website does)

That fix is in the new addon version 0.3.8 that has just been released
