### ISSUE TITLE
RWC 2019 - replays start near the end

### ISSUE THREAD

**Issue by PhilDaintree** [matthuisman/plugin.video.spark.sport#2]
Hi Matt,
Thanks for your work :-) Live streaming has been flawless.
However, watching the Wales vs SA replay on Monday morning the stream would not play from the beginning  it started with the Conrad Smith interview with Kim Downs after the game has finished! The stream works fine through a browser - so not a Spark issue. 
There is no option to scroll to the beginning of the game  through the add on as the slide bar is showing it is at the start - so it was not possible to view the replay through your add on. Sliding the slide bar over towards the middle ends the stream - as it close to the end where it starts

(No one in the familiy had watched the stream previously)

Thanks 
Phil

**Comment by matthuisman** [comment]
There is a warning about multiple periods when you play the stream.
That explains why this is happening.
Out of my hands until kodi supports that
